### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by ThankGod-Uzochukwu** [expo/orbit#201]
Please how can I install the expo orbit on my windows10 machine

**Comment by Saadnajmi** [comment]
You probably want to install the `.exe` from here https://github.com/expo/orbit/releases/tag/expo-orbit-v2.0.0-preview.1

**Comment by ThankGod-Uzochukwu** [comment]
ok, thank you

**Comment by ThankGod-Uzochukwu** [comment]
it worked
