### ISSUE TITLE
couldnt run in windows 8.1

### ISSUE THREAD

**Issue by Malazhasan** [expo/orbit#202]
### Summary

![Capture](https://github.com/expo/orbit/assets/121643124/03d3a510-84ee-48ec-81dd-eaffdd21556c)
couldnt run in windows 8.1 x64

### Steps to reproduce

couldnt run in windows 8.1 x64![Capture](https://github.com/expo/orbit/assets/121643124/2be48a99-79a0-46d9-9919-4e482136fd87)

### Environment

.

**Comment by Malazhasan** [comment]
![Capture](https://github.com/expo/orbit/assets/121643124/4ee0bfee-81eb-4f4d-a0b0-fb0fbc52af64)

**Comment by gabrieldonadel** [comment]
Hi @Malazhasan, thanks for reporting this bug. This might be something specific to Windows 8 but we will investigate what could be the root cause the get back to you soon
