### ISSUE TITLE
[Bug] Orbit not showing up in menu bar after setup screen

### ISSUE THREAD

**Issue by leohenworx** [expo/orbit#21]
After downloading Orbit, i moved it to the applications directory. Then i started it and got greeted with the setup screen. Both android and ios showed a green tick after a short waiting time. I then pressed "Get Started" and the window closed. After that nothing happened. Orbit did not show up in the menu bar, even after waiting for ~2 minutes. Then i closing Orbit in the activity manager and starting it again, but no luck. I still cant get it to show up.

<img width="318" alt="image" src="https://github.com/expo/orbit/assets/106064182/5acfea5c-6376-4064-b9d0-eb01a6a854e8">

> expo-env-info 1.0.5 environment info:
>     System:
>       OS: macOS 13.4
>       Shell: 5.9 - /bin/zsh
>     Binaries:
>       Node: 20.3.1 - ~/.nvm/versions/node/v20.3.1/bin/node
>       Yarn: 1.22.19 - ~/.yarn/bin/yarn
>       npm: 9.6.7 - ~/.nvm/versions/node/v20.3.1/bin/npm
>       Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
>     Managers:
>       CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
>     SDKs:
>       iOS SDK:
>         Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
>     IDEs:
>       Android Studio: 2021.2 AI-212.5712.43.2112.8512546
>       Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
>     npmGlobalPackages:
>       eas-cli: 4.0.1

**Comment by gabrieldonadel** [comment]
Hi @leohenworx, can you check if you have available space on your menu bar? Sometimes the icon may be hidden by the Macbook Pro notch, we had some reports of this issue on Discord and that was the problem

**Comment by leohenworx** [comment]
@gabrieldonadel I found the issue. It was a tool i installed some time ago called Hidden Bar, which hides menu items. Normally it displays a line and an arrow to extend, but it didnt display that anymore for some reason. I didnt remember that it was installed. Also Apple should really fix the menu bar behavior with notches... Thanks!
