### ISSUE TITLE
v1.2 error with mac intel

### ISSUE THREAD

**Issue by SylvainLx** [expo/orbit#214]
### Summary

i've got an error if i install new expo-orbit version 1.2 with my mac intel, i can't see my devices : Unable to invoke internal CLI: pkg/prelude/bootstrap.js:1872   

### Steps to reproduce

install 1.2 version in mac intel and check your devices : Warning

### Environment

?

**Comment by gabrieldonadel** [comment]
Sorry for the incovininece, fix coming soon

**Comment by evanstern** [comment]
Has this been fixed? I'm seeing it as well. I'm not on an intel though, I'm on Mac Silicon.
