### ISSUE TITLE
[Bug] - Layout breaking after going on "sleep" mode.

### ISSUE THREAD

**Issue by Noitham** [expo/orbit#22]
Installed and set up Orbit yesterday, today I've tried accessing it, and it shows like this:

<img width="350" alt="image" src="https://github.com/expo/orbit/assets/32934478/d6ba8aa6-5837-472c-9f27-3aa164d9abe5">

All I can describe is yesterday it worked and looked as expected, and today after opening the MacBook noticed it was showing like this.

Force quitting it from the Activity Monitor and re-opening it fixed it.

**Comment by gabrieldonadel** [comment]
Hi @Noitham, thanks for reporting this issue, I'll be looking into a fix later today

**Comment by gabrieldonadel** [comment]
Figured out how to reproduce this consistently and I'll be opening a PR fixing it in a few

Steps to reproduce: 
1. Open the Popover on a second monitor
2. Put your Mac to sleep from the second monitor
3. Unplug the monitor
4. Wake up your Mac and press the Orbit Icon on the menu bar

**Comment by gabrieldonadel** [comment]
A new version of Expo Orbit has just been released! [v0.1.1](https://github.com/expo/orbit/releases/tag/expo-orbit-v0.1.1) includes fixes for this and other issues, you can check the full details on the [releases page](https://github.com/expo/orbit/releases). Please test it out and let us know if you find any other problems.
