### ISSUE TITLE
Orbit 2.0.0 on Mac: "`new NativeEventEmitter()` requires a non-null argument" after clicking "See all"

### ISSUE THREAD

**Issue by wodin** [expo/orbit#224]
### Summary

When I click on the "See all" option next to the "Projects" header, a new browser tab opens to `https://expo.dev/accounts/%5Baccount%5D/projects` as expected. The next time I click on the Orbit icon I get the following error and have to restart it.

<img width="452" alt="Error screenshot" src="https://github.com/user-attachments/assets/e0a8822d-d55e-4c52-b34c-03ba596f4c99">

### Steps to reproduce

* Start Orbit
* Open the Orbit menu and click on "See all" to the right of "Projects"
* Open the Orbit menu again

https://github.com/user-attachments/assets/cb8998c7-8370-451e-ad51-437ca71c9034

### Environment

```
  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.18.0 - /opt/homebrew/opt/node@20/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@20/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 13.3.0
      expo-cli: 6.3.12
    Expo Workflow: managed
```

**Comment by Saadnajmi** [comment]
@tido64 gave me a lead, we probably need to check for macOS here (we do that elsewhere): https://github.com/microsoft/react-native-macos/blob/6270064689d350905d98b96197df2358a74ce66e/packages/react-native/src/private/animated/NativeAnimatedHelper.js#L433

**Comment by gabrieldonadel** [comment]
> @tido64 gave me a lead, we probably need to check for macOS here (we do that elsewhere): https://github.com/microsoft/react-native-macos/blob/6270064689d350905d98b96197df2358a74ce66e/packages/react-native/src/private/animated/NativeAnimatedHelper.js#L433

Good call, let me patch that for now

**Comment by gabrieldonadel** [comment]
@Saadnajmi, I just tested changing that line and indeed it fixes it!
