### ISSUE TITLE
does not show the list of ios simulators nor android, can not select build

### ISSUE THREAD

**Issue by Aris-ngoy** [expo/orbit#23]
![Screenshot 2023-08-10 at 11 14 46](https://github.com/expo/orbit/assets/20087512/ed82dd10-204e-4354-978e-01b71496350b)

**Comment by gabrieldonadel** [comment]
Hi @Aris-ngoy, do you have Xcode and/or Android Studio installed? 

Also, can you paste the output of `npx expo-env-info` here?

**Comment by gabrieldonadel** [comment]
A new version of Expo Orbit has just been released! [v0.1.1](https://github.com/expo/orbit/releases/tag/expo-orbit-v0.1.1) includes fixes for this and other issues, you can check the full details on the [releases page](https://github.com/expo/orbit/releases). Please test it out and let us know if you find any other problems.
