### ISSUE TITLE
Very strange layout on macOS Sonoma

### ISSUE THREAD

**Issue by PatrikTheDev** [expo/orbit#30]
### Summary

<img width="480" alt="image" src="https://github.com/expo/orbit/assets/25883885/048ef16b-f8ea-4d01-8448-6f1e5b857df9">
<img width="480" alt="image" src="https://github.com/expo/orbit/assets/25883885/199f100b-ca85-47f0-9c97-ada6cb809657">
<img width="512" alt="image" src="https://github.com/expo/orbit/assets/25883885/d74894a5-80b5-4fdc-8772-10d5132713d6">

### Steps to reproduce

Just launched the app for the first time

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.6.0 - /opt/homebrew/bin/fish
    Binaries:
      Node: 20.3.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild

**Comment by Saadnajmi** [comment]
macOS Sonoma added a change by adding `NSView.clipsToBounds` as a property, and a breaking change of changing `drawRect` to give you rects that can very much draw outside the bounds of your views. RN-SVG uses drawRect in its implementation, and we saw similar issues in our apps with Sonoma. Fix would be in react-native-svg

**Comment by PatrikTheDev** [comment]
How about the last screenshot? The settings page rendered incorrectly upon the first launch, though subsequent launches looked fine

**Comment by Saadnajmi** [comment]
I found another explainer: https://indiestack.com/2023/06/view-clipping-sonoma/
I'm not sure what's happening with the settings page, but I know React Native macOS <Text> overrides drawRect to I'm pretty sure, so there might be an issue there too.

**Comment by gabrieldonadel** [comment]
> How about the last screenshot? The settings page rendered incorrectly upon the first launch, though subsequent launches looked fine

I'll take a look at that

**Comment by idrakimuhamad** [comment]
Had this too in Sonoma. But goes away after sleep.

![image](https://github.com/expo/orbit/assets/1400323/30f46d47-bddc-48d8-91b9-aa7e1832bfaa)

**Comment by gabrieldonadel** [comment]
A new version of Expo Orbit has just been released! [v0.1.3](https://github.com/expo/orbit/releases/tag/expo-orbit-v0.1.3) includes fixes for this and other issues, you can check the full details on the [releases page](https://github.com/expo/orbit/releases). Please test it out and let us know if you find any other problems.
