### ISSUE TITLE
Manage tvOS simulator with Orbit

### ISSUE THREAD

**Issue by JulienIzz** [expo/orbit#81]
### Is your feature request related to a problem? Please describe.

I started a project with react-native-tv-os and managed to get my Android TV simulator on the Orbit list as shown here : 
<img width="400" alt="image" src="https://github.com/expo/orbit/assets/103206306/f1bf7f81-f415-44c7-a94a-9b4adfbbe2d5">

But none of the tvOS simulator appear on the list. I suspect it's because iOS and tvOS simulator are managed differently by XCode ?

### Describe the solution you'd like

An ideal solution would be to show another list (at the moment there is iOS and Android) with tvOS devices.

**Comment by gabrieldonadel** [comment]
Hi @JulienIzz, thank you for opening this issue. 

The ability to list tvOS simulators is actually something that we're already working on (https://github.com/expo/orbit/pull/77) and will be included on the next release

**Comment by gabrieldonadel** [comment]
A new version of Expo Orbit has just been released! [v1.0.0](https://github.com/expo/orbit/releases/tag/expo-orbit-v1.0.0) includes fixes for this and other issues, you can check the full details on the [releases page](https://github.com/expo/orbit/releases). Please test it out and let us know if you find any other problems.

**Comment by gabrieldonadel** [comment]
You can now enable tvOS through the Settings window
<img width="612" alt="image" src="https://github.com/expo/orbit/assets/11707729/f6adb2b0-3ffb-414b-aa5d-a2472805da86">
